### ISSUE TITLE
[Bug] v2.2.11 TypeError: e.contains is not a function — 话题参数无法传递（模型选择、自动压缩等）

### ISSUE THREAD

**Issue by panghu0516** [lobehub/lobehub#17548]
### 📦 Environment

- **Version:** v2.2.11 (Desktop App)
- **Previous working version:** v2.2.10
- **OS:**Windows
- **Browser (if applicable):**  Edge

### 🐛 Bug Description

After upgrading from v2.2.10 to v2.2.11, the desktop (and web) UI repeatedly throws:

Uncaught TypeError: e.contains is not a function
at K (imperative-d7IpQ_lH.js:162:13020)
at Os (imperative-d7IpQ_lH.js:162:13353)
at HTMLDivElement.i (imperative-d7IpQ_lH.js:162:92771)

*.txt
Plaintext
Also appears from `Qm.hasMatchingElement` path:
Uncaught TypeError: e.contains is not a function
at K (imperative-d7IpQ_lH.js:162:13020)
at Qm.hasMatchingElement (imperative-d7IpQ_lH.js:162:80631)
at j (imperative-d7IpQ_lH.js:162:45207)

*.txt
Plaintext
The error floods the console on page load and on click interactions.
### Impact
1. **Topic-level parameters cannot be saved/applied** — selecting a different model for a topic, toggling auto history compression, or changing any topic-level setting has no effect. The state change appears to crash before persistence.
2. **UI becomes unresponsive** — dropdown menus and floating panels sometimes fail to close or refresh properly, leaving the UI in a broken state.
3. Also see browser warning: `The label's for attribute doesn't match any element id` — suggesting form element ID mismatches in the topic settings panel.
### Root Cause Analysis
The error occurs in the `imperative-*.js` chunk, which is from the `@floating-ui/react` library (or a similar DOM manipulation utility). The `contains()` method is a `Node.contains()` DOM call. When a floating panel's `activeElement` or DOM reference becomes `null`/`undefined`, calling `.contains()` on it throws this TypeError.
This is a regression introduced in v2.2.11, which contained 366 merged PRs including topic-level model selection (#15933) and UI refactoring that likely affected the floating component lifecycle.
### Steps to Reproduce
1. Start a new topic in any agent
2. Try to change the model for the topic (or toggle any topic-level setting)
3. Observe that the selection does not persist / the dropdown behaves incorrectly
4. Open DevTools console → see `e.contains is not a function` errors flooding
Or simply open the app on v2.2.11 — the errors may appear on page load depending on saved state.
### Expected Behavior
- Topic parameters (model selection, history compression toggle, etc.) should be saved and applied correctly
- No `e.contains is not a function` errors in console
- UI should remain responsive
### Workaround
Rolling back to v2.2.10 resolves the issue.
### Additional Info
- Reproducible in both incognito mode and desktop app
- Not a cache/browser issue — confirmed by testing in incognito with clean state
- Also reproduced on web version (Docker deployment) after upgrading to v2.2.11
